Invisible Skeleton Chance: 10
  Invisible Skeleton Health: 1
  
Jump Skeleton Chance: 30
  Jump Skeleton Health: 1
  Jump Skeleton Jump: 1
  
Speed Skeleton Chance: 30
  Speed Skeleton Health: 1
  Speed Skeleton Speed: 1
  
Strength Skeleton Chance: 30
  Strength Skeleton Health: 1
  Strength Skeleton Damage: 30